# Actividad: Entrenamiento de redes neuronales (2)



*   Alfredo Romo Osorno | A01643235
*   Jorge Alejandro Gonzales Díaz | Axxxxxxxx
*   Pablo Vargas Cárdenas | Axxxxxxxx



1.   Ajusta un modelo perceptrón multicapa para [este conjunto de datos](https://experiencia21.tec.mx/courses/554073/files/226526780/download?download_frd=1) con dos clases y evalúa su rendimiento con validación cruzada.  

In [51]:
#### Libraries Import ####
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

import matplotlib.pyplot as plt
##################################################

In [ ]:
# Load txt into DF
data_dir = "./data_2_1.txt"
data_array = np.loadtxt(data_dir)
df = pd.DataFrame(data_array)

# Separate class and predictors
y = df.iloc[:, 0].values      # first column as class
X = df.iloc[:, 1:].values     # remaining columns as predictors
y = np.where(y == 2, 1, 0)    # mat to {1,0} since we're doing a binary classifier

y, X



# Split the dataset into training and testing sets (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_train, X_train

(array([1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
        0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 

In [41]:
# Crete model 
def create_model(input_dim):
    model = keras.Sequential([
        layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        layers.Dense(32, activation='relu'),
        layers.Dense(1, activation='sigmoid')  # Binary output
    ])
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model


In [42]:
X = np.concatenate([X_train, X_test])
y = np.concatenate([y_train, y_test])


In [43]:
print(X.shape)
k = 5  # Number of folds
skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
accuracies = []

for train_index, val_index in skf.split(X, y):
    X_train_fold, X_val_fold = X[train_index], X[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]

    model = create_model(input_dim=X.shape[1])
    model.fit(X_train_fold, y_train_fold, epochs=20, batch_size=32, verbose=0)
    
    y_pred = (model.predict(X_val_fold) > 0.5).astype("int32").flatten()
    acc = accuracy_score(y_val_fold, y_pred)
    accuracies.append(acc)
    print(f"Fold accuracy: {acc:.4f}")

print(f"\nAverage accuracy over {k} folds: {np.mean(accuracies):.4f}")


(528, 153)


/home/fredi/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 164ms/step
Fold accuracy: 0.7453


/home/fredi/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
Fold accuracy: 0.8396


/home/fredi/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
Fold accuracy: 0.8208


/home/fredi/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
Fold accuracy: 0.7714


/home/fredi/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
Fold accuracy: 0.8000

Average accuracy over 5 folds: 0.7954


2.   Ajusta un modelo perceptrón multicapa para [este otro conjunto de datos](https://experiencia21.tec.mx/courses/554073/files/226526779/download?download_frd=1) de cuatro clases y evalúa su rendimiento con validación cruzada.

In [58]:
from tensorflow.keras.utils import to_categorical

# Load txt into DF
data_dir = "./data_2_2.txt"
data_array = np.loadtxt(data_dir)
df = pd.DataFrame(data_array)

# Separate class and predictors
y = df.iloc[:, 0].values      # first column as class
X = df.iloc[:, 1:].values     # remaining columns as predictors
#y = np.where(y == 2, 1, 0)    # map to {1,0} since we're doing a binary classifier

y, X



# Split the dataset into training and testing sets (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_train, X_train

(array([4., 3., 2., 2., 3., 1., 3., 4., 4., 4., 2., 4., 2., 4., 2., 3., 2.,
        4., 3., 4., 3., 2., 3., 2., 1., 2., 3., 3., 4., 2., 4., 3., 1., 4.,
        4., 4., 4., 1., 1., 3., 3., 2., 2., 3., 2., 4., 3., 1., 1., 1., 1.,
        1., 2., 2., 1., 3., 2., 3., 2., 1., 2., 2., 2., 3., 4., 2., 1., 2.,
        3., 2., 3., 1., 4., 3., 2., 4., 3., 1., 4., 2., 4., 3., 2., 1., 1.,
        3., 3., 1., 4., 4., 1., 3., 1., 2., 1., 4., 3., 3., 1., 3., 2., 4.,
        4., 2., 4., 2., 1., 4., 3., 1., 2., 3., 1., 4., 3., 2., 1., 4., 1.,
        2., 4., 3., 1., 3., 3., 1., 2., 1., 3., 4., 4., 4., 1., 3., 2., 1.,
        4., 1., 3., 4., 2., 2., 2., 4., 4., 2., 1., 1., 1., 4., 3., 1., 3.,
        2., 4., 3., 4., 4., 1., 1., 2., 1., 4., 3., 4., 3., 1., 4., 4., 4.,
        3., 1., 4., 1., 2., 1., 1., 4., 3., 4., 3., 3., 3., 1., 3., 4., 4.,
        1., 1., 3., 3., 3., 2., 2., 2., 2., 4., 2., 4., 4., 2., 4., 1., 3.,
        2., 2., 2.]),
 array([[-0.66050786, -0.44611915, -0.44611915, ...,  0.00480801,


In [54]:
def create_model(input_dim, num_classes):
    model = keras.Sequential([
        keras.Input(shape=(input_dim,)),
        layers.Dense(64, activation='relu'),
        layers.Dense(32, activation='relu'),
        layers.Dense(num_classes, activation='softmax')  # Multiclass output
    ])
    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    return model


In [60]:
from sklearn.model_selection import StratifiedKFold
from tensorflow.keras.utils import to_categorical
y_raw = y - 1  # Converts [1, 2, 3, 4] → [0, 1, 2, 3]


skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for train_idx, val_idx in skf.split(X, y_raw):
    X_train, X_val = X[train_idx], X[val_idx]
    y_train = to_categorical(y_raw[train_idx], num_classes=4)
    y_val = to_categorical(y_raw[val_idx], num_classes=4)

    model = create_model(input_dim=X.shape[1], num_classes=4)
    model.fit(X_train, y_train, epochs=20, batch_size=32, verbose=0)

    y_pred = model.predict(X_val)
    pred_labels = np.argmax(y_pred, axis=1)
    true_labels = np.argmax(y_val, axis=1)

    acc = accuracy_score(true_labels, pred_labels)
    print(f"Fold accuracy: {acc:.4f}")


2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 261ms/step
Fold accuracy: 0.9423
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 208ms/step
Fold accuracy: 1.0000
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 240ms/step
Fold accuracy: 0.9615
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 208ms/step
Fold accuracy: 0.9808
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step
Fold accuracy: 0.9020


3. Para el [conjunto de datos diabetes](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html) ajusta un modelo de regresión perceptrón multicapa, y evalúa el error cuadrático medio del modelo con validación cruzada.

In [67]:
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

In [72]:
# Load the dataset
from sklearn.datasets import load_diabetes
data = load_diabetes()
X = data.data
y = data.target

In [65]:
def create_regression_model(input_dim):
    model = keras.Sequential([
        keras.Input(shape=(input_dim,)),
        layers.Dense(64, activation='relu'),
        layers.Dense(32, activation='relu'),
        layers.Dense(1)  # No activation — we're predicting a number
    ])
    model.compile(optimizer='adam', loss='mse', metrics=['mse'])
    return model


In [66]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)
mse_scores = []

for train_idx, val_idx in kf.split(X):
    X_train, X_val = X[train_idx], X[val_idx]
    y_train, y_val = y[train_idx], y[val_idx]

    model = create_regression_model(input_dim=X.shape[1])
    model.fit(X_train, y_train, epochs=100, batch_size=16, verbose=0)

    y_pred = model.predict(X_val).flatten()
    mse = mean_squared_error(y_val, y_pred)
    mse_scores.append(mse)
    print(f"Fold MSE: {mse:.2f}")

print(f"\nAverage MSE over 5 folds: {np.mean(mse_scores):.2f}")


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
Fold MSE: 2850.95
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
Fold MSE: 2732.40
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
Fold MSE: 3262.95
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
Fold MSE: 2789.88
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
Fold MSE: 3378.82

Average MSE over 5 folds: 3003.00
